# Form implementation generated from reading ui file '/media/nemsys/data/projects/courses/ProgressBG/ProgressBG-Python/ProgressBG-Python-Labs/Lab16/gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOK = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnOK.setGeometry(QtCore.QRect(40, 70, 191, 23))
        self.btnOK.setObjectName("btnOK")
        self.leUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leUserName.setGeometry(QtCore.QRect(120, 20, 113, 22))
        self.leUserName.setObjectName("leUserName")
        self.lblUserName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUserName.setGeometry(QtCore.QRect(40, 20, 68, 15))
        self.lblUserName.setObjectName("lblUserName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOK.setText(_translate("MainWindow", "OK"))
        self.lblUserName.setText(_translate("MainWindow", "user name: "))
